global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: elixir
  scrape_interval: 15s
  static_configs:
  - targets:
    - elixir_exporter:4040
